/* Theory-first lesson presentation. This additive file leaves certification untouched. */
const uses={
  python:'Python is used to automate work, build websites and APIs, analyze data, test software, and create AI applications.',
  snowflake:'Snowflake is used to store, transform, govern, and share business data in a cloud data platform.',
  databricks:'Databricks is used to engineer data, run distributed analytics, and build machine-learning workflows.',
  'ethical-hacking':'Ethical hacking is used, with written authorization, to find weaknesses so organizations can fix them.',
  'cyber-security':'Cyber Security is used to protect people, systems, networks, and data from avoidable harm.',
  'ai-ml':'AI and machine learning are used to find patterns, make predictions, automate decisions, and build intelligent products.'
};
function learnerSteps(topic,track){return [`Read the simple explanation and say it back in your own words.`,`Copy the basic example and identify its input, action, and output.`,`Follow the easy lab step by step; change only one thing.`,`Compare your result with the expected result and write what changed.`,`Complete medium and hard labs only after the easy version works.`]}
function lesson(id,lid,tid){const t=catalog.tracks.find(x=>x.id===id),l=t.levels.find(x=>x.id===lid),x=l.topics.find(x=>x.id===tid),steps=learnerSteps(x.title,id);out.innerHTML=`<p class="crumb" data-back>← ${esc(t.name)} · ${esc(l.name)}</p><article class="panel"><span class="badge">Step-by-step theory lesson</span><h1>${esc(x.title)}</h1><section class="lesson-section"><h2>1. What is ${esc(t.name)} used for?</h2><p>${esc(uses[id])}</p></section><section class="lesson-section"><h2>2. Why learn this concept?</h2><p>${esc(x.why)}</p></section><section class="lesson-section"><h2>3. Simple explanation</h2><p>${esc(x.explanation)}</p><p><strong>Think of it like this:</strong> ${esc(x.analogy)}</p></section><section class="lesson-section"><h2>4. Deeper explanation</h2><p>${esc(x.underHood)}</p><p>${esc(x.summary)}</p></section><section class="lesson-section"><h2>5. Basic example</h2><pre><code>${esc(x.example)}</code></pre><p>${esc(x.exampleNote)}</p></section><section class="lesson-section"><h2>6. Practice it step by step</h2><ol>${steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section class="lesson-section"><h2>7. Common mistakes</h2><ul>${x.mistakes.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><h2>Best practices</h2><ul>${x.best.map(a=>`<li>${esc(a)}</li>`).join('')}</ul></section><section class="lesson-section"><h2>8. Hands-on labs</h2><p>Start with Easy. Do not jump to Hard until you can explain the Easy result.</p>${labsHtml(t,x)}</section><section class="lesson-section"><h2>9. Test yourself</h2><p>${esc(x.quiz.q)}</p>${x.quiz.options.map((a,i)=>`<label class="level"><input type="radio" name="quiz" value="${i}"> ${esc(a)}</label>`).join('')}<button class="secondary" id="checkQuiz">Check answer</button><p id="quizOut"></p></section></article>`;$('[data-back]').onclick=()=>track(id,lid);$('#checkQuiz').onclick=()=>{const v=document.querySelector('input[name=quiz]:checked')?.value;$('#quizOut').textContent=v===undefined?'Choose an answer.':Number(v)===x.quiz.answer?'Correct — '+x.quiz.explanation:'Try again: '+x.quiz.explanation};bindLabs(t,x)}
