/* Plain-language software actions and a local, privacy-first troubleshooting helper. */
const softwareActions={
  python:{where:'your Python editor and terminal',steps:['Open the project folder in your editor.', 'Open its built-in terminal.', 'Activate the project environment if you created one.', 'Create or open the lesson file, then copy only the small example from the lesson.', 'Run it with python filename.py and compare the result with “You should see”.'],checks:['Check the file name and folder first.', 'Run python --version to confirm the interpreter is available.', 'Read the final line of the error first; it usually names the immediate problem.']},
  snowflake:{where:'a Snowflake worksheet in your approved training account',steps:['Open Worksheets and create a new worksheet in your personal training area.', 'Select the permitted warehouse, database, and schema shown by your training account.', 'Paste one SQL statement only, then run it.', 'Read the Results tab before running a second statement.', 'Suspend unused training compute when you finish.'],checks:['Check the selected role, warehouse, database, and schema.', 'Read the first SQL error line and the line/position it reports.', 'Use only objects you own or are explicitly allowed to use.']},
  databricks:{where:'a notebook in your approved Databricks workspace',steps:['Open your personal training folder and create/open a notebook.', 'Choose the language named in the lesson: Python or SQL.', 'Attach only approved training compute.', 'Run one cell at a time and inspect the output under that cell.', 'Stop/disconnect unused compute when you finish.'],checks:['Check that compute is running and you have permission to use it.', 'Check the notebook language and the first failing line.', 'Do not paste access tokens, customer data, or internal URLs into a notebook.']},
  'ethical-hacking':{where:'your isolated, authorised security-learning sandbox only',steps:['Re-read the written scope before touching a tool.', 'Confirm the target is your private lab and not connected to public, workplace, or home systems.', 'Use the simulated exercise or evidence file named by the lesson.', 'Record observation, risk, and defensive remediation.', 'Restore the lab snapshot when the exercise ends.'],checks:['Stop if the target or permission is unclear.', 'Do not scan, probe, or attack any real/public system.', 'Keep credentials and personal data out of evidence notes.']},
  'cyber-security':{where:'your local defensive practice folder or isolated training lab',steps:['Open the fictional sample log, policy, or scenario from the lesson.', 'Identify the asset, threat, protection, and evidence before choosing an answer.', 'Work one event or control at a time.', 'Record your decision and the reason for it.', 'Compare with the lesson’s safe solution or checklist.'],checks:['Use fictional/sanitised data only.', 'Check timestamps, user/device IDs, and event order in log scenarios.', 'Do not change real production security controls while learning.']},
  'ai-ml':{where:'your Python project folder or approved notebook workspace',steps:['Open the lesson notebook or Python project.', 'Activate the project environment before installing/running packages.', 'Run one small data/model cell at a time.', 'Inspect shape, column names, metric, and output before changing settings.', 'Save the seed, package versions, and result notes.'],checks:['Confirm Python environment and packages are installed.', 'Check data shape/type and missing values before model code.', 'Use public, fictional, or anonymised data only—never secrets or private records.']}
};
function softwareGuideHTML(trackId){const guide=softwareActions[trackId];if(!guide)return '';return `<section class="lesson-section software-howto"><h2>Do this in the software</h2><p>Use this lesson in <strong>${esc(guide.where)}</strong>.</p><ol>${guide.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><h3>If it does not work, check these first</h3><ul>${guide.checks.map(check=>`<li>${esc(check)}</li>`).join('')}</ul></section>`}
const helpPatterns=[
  {tracks:['python','ai-ml'],match:/modulenotfounderror|no module named/i,title:'Python cannot find a package',meaning:'Python is running, but the current environment does not contain the package named in the error.',steps:['Activate the project environment (.venv) in the same terminal that runs your file.', 'Run python --version and python -m pip --version; both should point to the same environment.', 'Install the required package with python -m pip install package-name, replacing package-name with the name from the lesson.', 'Run the program again. Do not install packages into a random/global environment if the project uses .venv.']},
  {tracks:['python','ai-ml'],match:/indentationerror|unexpected indent/i,title:'Python indentation problem',meaning:'Python uses spaces at the start of a line to decide which instructions belong together.',steps:['Look at the line number shown in the error and the line immediately above it.', 'Use consistent indentation—normally four spaces—for lines inside if, for, while, def, class, try, or with blocks.', 'Do not mix tabs and spaces. Use your editor’s “convert indentation to spaces” option if available.', 'Run the smallest corrected example again.']},
  {tracks:['python','ai-ml'],match:/syntaxerror/i,title:'Python syntax problem',meaning:'Python could not read the instruction as valid Python.',steps:['Read the final error line and the caret (^) location.', 'Check the previous line too; a missing quote, bracket, colon, or comma often causes the next line to be highlighted.', 'Compare the line with the small lesson example rather than rewriting the whole program.', 'Fix one issue, save, and run again.']},
  {tracks:['snowflake'],match:/does not exist|not authorized|insufficient privileges/i,title:'Snowflake object or permission problem',meaning:'The selected role may not be allowed to see the object, or the database/schema/object name is not the one you intended.',steps:['Check the currently selected role, warehouse, database, and schema in the worksheet.', 'Confirm spelling and whether the object was created with quoted case-sensitive identifiers.', 'Use only your permitted training objects; do not try to bypass permissions.', 'If access is genuinely required, ask the training-account administrator for the minimum required role.']},
  {tracks:['snowflake'],match:/warehouse.*(suspend|not running)|no active warehouse/i,title:'Snowflake warehouse is not ready',meaning:'The query has no active permitted compute warehouse selected.',steps:['Select the small approved training warehouse in the worksheet.', 'If you are allowed to resume it, resume only that warehouse.', 'Run the small lesson query again.', 'Suspend the warehouse after practice if your account policy allows it.']},
  {tracks:['databricks'],match:/cluster.*(not running|terminated)|compute.*(not running|terminated)/i,title:'Databricks compute is not running',meaning:'The notebook cannot execute until approved compute is attached and available.',steps:['Open the notebook’s compute selector.', 'Choose the approved training compute or request access from the workspace administrator.', 'Wait until the status is Running, then rerun only the failed cell.', 'Disconnect or stop unused training compute when finished.']},
  {tracks:['databricks'],match:/analysisexception|cannot resolve|unresolved column/i,title:'Databricks cannot find a column or table',meaning:'The DataFrame/table name or a column in the command does not match the available data.',steps:['Display the schema or table columns before changing the transformation.', 'Check spelling, case, punctuation, and whether the correct catalog/schema/table is selected.', 'Use one small select/display step to confirm the name.', 'Then rerun the transformation. Do not guess or rename production data while learning.']},
  {tracks:['ethical-hacking'],match:/.*/i,title:'Safety-first ethical-hacking troubleshooting',meaning:'Security exercises must stay within written scope and an isolated sandbox. The safest first response to an unexpected tool result is to stop and verify the environment.',steps:['Confirm the target is your authorised private lab and the exercise is within written scope.', 'Do not run the command against any public, workplace, home, or third-party system.', 'Check the lesson’s simulated target, expected evidence, and defensive goal.', 'If the error involves a real IP address, credential, or external hostname, remove it before asking for help and use a fictional/sandbox example instead.']},
  {tracks:['cyber-security'],match:/.*/i,title:'Defensive troubleshooting checklist',meaning:'Start by protecting evidence and understanding the context before changing anything.',steps:['Use only fictional/sanitised logs or your authorised lab data.', 'Check timestamp, asset, account, and event order.', 'State what normal behaviour would look like, then identify the difference.', 'Choose a reversible defensive next step and record why you chose it.']}
];
function helpAgent(){const trackOptions=(catalog?.tracks||[]).map(track=>`<option value="${esc(track.id)}">${esc(track.name)}</option>`).join('');out.innerHTML=`<p class="crumb"><a href="#home">← Dashboard</a></p><article class="panel help-agent"><div class="lesson-meta"><span class="badge">LearnVerse Help Agent</span><span>Privacy-first local guidance</span></div><h1>Paste an error. Get a clear next step.</h1><p class="lesson-lead">Choose the track, paste the error message, and get a plain-language explanation plus safe troubleshooting steps from this course’s knowledge base.</p><section class="start-here"><h2>Before you paste anything</h2><p>Remove passwords, API keys, access tokens, private URLs, personal data, customer data, and real IP addresses. The agent cannot access your computer or run commands for you.</p></section><label class="field-label">Learning track<select id="helpTrack">${trackOptions}</select></label><label class="field-label">Error message or what happened<textarea id="helpError" rows="8" placeholder="Example: ModuleNotFoundError: No module named 'pandas'"></textarea></label><button class="primary" id="askHelp">Explain this error →</button><section class="lesson-section help-answer" id="helpAnswer" aria-live="polite"><p>Paste an error above. You will get the first safe checks, not a confusing wall of technical text.</p></section></article>`;$('#askHelp').onclick=()=>{const trackId=$('#helpTrack').value,error=$('#helpError').value.trim();if(!error){$('#helpAnswer').innerHTML='<p>Please paste the error message or describe what happened first.</p>';return;}const found=helpPatterns.find(pattern=>pattern.tracks.includes(trackId)&&pattern.match.test(error))||{title:'Start with the first error line',meaning:'This exact message is not yet in the local troubleshooting guide. Use the safe first checks below, then compare the error with the lesson you were following.',steps:['Read the final error line and note its line number.', 'Check the lesson’s expected result and the first software step.', 'Undo only the last change, then rerun the smallest example.', 'If you need more help, paste a sanitised error with the track and lesson name—never secrets or private data.']};$('#helpAnswer').innerHTML=`<h2>${esc(found.title)}</h2><p>${esc(found.meaning)}</p><h3>Try these steps in order</h3><ol>${found.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><p><strong>Still stuck?</strong> Copy only the sanitised error, the lesson name, and the step you were on. Do not include credentials or real/private data.</p>`};}
function helpRoute(){if(location.hash==='#help-agent'&&catalog)helpAgent()}
window.addEventListener('hashchange',helpRoute);window.addEventListener('load',helpRoute);
